# CIL exercise k-means clustering

In [ ]:
%matplotlib inline

import matplotlib
import numpy as np
import matplotlib.pyplot as plt
# pip3 install Pillow
import os,sys
from PIL import Image
import os
import time

In [ ]:
#np.array because then we can find the uncompressed size later
im = np.array(Image.open('eth.jpg'))
im2 = np.array(Image.open('tokara.jpg'))

In [ ]:
plt.imshow(im)

In [ ]:
plt.imshow(im2)

In [ ]:
#what is the uncompressed size of this image considering only pixels
print('Resolution:', im.shape)
print('Uncompressed size:', np.product(im.shape), 'bytes')

print('Resolution:', im2.shape)
print('Uncompressed size:', np.product(im2.shape), 'bytes')

We need to transform the image to a set of points/vectors, such that we can run the clustering algorithm on it. We will treat each pixel as a 3D vector (1 dimension per color channel R,G and B)

In [ ]:
#we will continue with the first image
height = 606
width = 465
channels = 3
#each pixel is a vector with dim number colour channels
pixels = im.reshape(height*width,channels)

In [ ]:
pixels[0]

In [ ]:
def initialize(X,k):
    cc = np.random.choice(X.shape[0], k, replace=False)
    return cc

In [ ]:
#these are examples of cluster centroids (1D)
cc = initialize(pixvec, 4)

In [ ]:
def assign_clusters(X,U):
    """"
    Compute the cluster to which each point belongs by finding the
    centroid it is closest to
    return: 
    """
    distances = np.sum((X[:, np.newaxis] - U[np.newaxis, :])**2, axis=2) # Squared
    #because the new axis = 1 and at this new axis
    #we store the subtraction of the pixel and all the cluster
    #centroids
    z = np.argmin(distances, axis=1)
    return(z)
    
    

In [ ]:
pixels.copy()[:,np.newaxis].shape

In [105]:
thing = pixels.copy()[:,np.newaxis] - U[np.newaxis,:]

In [108]:
print(thing.shape)

(281790, 16, 3)


In [99]:
assign_clusters(pixels.copy(),U)

[[321 224  16 ... 169  48 451]
 [321 224  16 ... 169  48 451]
 [321 224  16 ... 169  48 451]
 ...
 [248 181 229 ... 490 117 418]
 [504  85 261 ... 234 149 162]
 [387 162 170 ... 357 330 205]]
(281790, 16)


array([2, 2, 2, ..., 4, 1, 6])

In [90]:
def compute_centroids(points,z,k):
    centroids = []
    for i in range(k):
        points_k = points[z==i]
        if len(points_k) > 0:
            centroids.append(np.mean(points_k,axis=0))
    return np.array(centroids), len(centroids)

In [91]:
def do_loop(X,U,z,k):
    
    converged = False
    dropped = 0
    
    while(not converged and k>0):
        #step1
        U, l = compute_centroids(X,z,k)
        dropped += k-l
        k = l
        #step2
        z_new = assign_clusters(X,U)
        convergence = (z == z_new).all()
        z = z_new
    return U,z,k
        
        

In [ ]:
k = 16
X = pixels.copy()
U = X[np.random.choice(X.shape[0], size = k, replace=False)]
z = assign_clusters(X,U)

start_time = time.time()
U,z,k = do_loop(X,U,z,k)
end_time = time.time()

In [94]:
print(U)

[[196 244 254]
 [170 226 253]
 [ 22  26  29]
 [181 179 158]
 [ 11  13  10]
 [ 86  88  74]
 [ 99 101  87]
 [ 62  63  55]
 [ 91  88  69]
 [182 179 162]
 [223 253 255]
 [ 64  67  58]
 [153 206 250]
 [ 54  55  49]
 [154 206 253]
 [ 29  61  76]]


In [ ]:
Now we will show the compressed image. For this we need to replace each point by the 
cluster centroid we assigned it to.

In [ ]:
#. Displaying the compressed image against the original one
fig, ax = plt.subplots(1,2,figsize=(15,15))
ax[0].imshow(data) # this is the original image 
ax[0].set_title("Original")
compressed_image = X.reshape(height,width,3)
ax[1].imshow(compressed_image) # this is the compressed one
ax[1].set_title("Compressed")
pyplot.show()
